// Generated by https://quicktype.io

export interface AutoModel {
    model_id:            string;
    name:                string;
    photo_sha:           string;
    dealer_exist:        DealerExist;
    dealer_ids:          string[];
    min_price:           string;
    modifications:       Modification[];
    colors:              Color[];
    modification_photos: any[];
}

export interface Color {
    color_id:         string;
    name:             string;
    hex_value:        string;
    note:             Note;
    photo_sha:        string;
    modification_ids: any[];
}

export enum Note {
    KoK = "Ko'k",
    Kulrang = "Kulrang",
    Oq = "Oq",
    Qizil = "Qizil",
    Qora = "Qora",
}

export enum DealerExist {
    N = "N",
    Y = "Y",
}

export interface Modification {
    modification_id: string;
    name:            string;
    price:           string;
    min_price:       string;
    color_margins:   any[];
    producing:       DealerExist;
    options:         string[];
    options_obj:     OptionsObj[];
}

export interface OptionsObj {
    name:        string;
    description: string;
    imagesha:    string;
}
